
context:
  name: vhs
  version: 0.7.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/charmbracelet/${{ name }}/archive/refs/tags/v0.7.2.tar.gz
    sha256: 9be4b88a638336f6bba913f391b0300549280246e08d26cbd5053b63c60ee40c
    target_directory: src
  # https://github.com/mattn/go-localereader/issues/2
  - url: https://github.com/mattn/go-localereader/raw/master/LICENSE
    sha256: dceede03550621e65ec7b79fcba87cf6dbb9d31132a8ae71a8fe8ceec0af7da3

build:
  number: 0
  script:
    - mv LICENSE go-localereader-LICENSE
    - cd src
    - go-licenses save . --ignore github.com/mattn/go-localereader --save_path=../library_licenses
    - if: not win
      then: go build -v -o $PREFIX/bin/vhs
    - if: win
      then: go build -v -o %LIBRARY_BIN%\vhs.exe
    # Clear out cache to avoid file not removable warnings
    - if: unix
      then: chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - vhs --version

about:
  summary: Your CLI home video recorder
  license: MIT
  license_file:
    - src/LICENSE
    - library_licenses/
    - go-localereader-LICENSE
  homepage: https://github.com/charmbracelet/vhs
  repository: https://github.com/charmbracelet/vhs

extra:
  recipe-maintainers:
    - pavelzw
